version: "*3.9"
services:
  django_todo_app:
    container_name: "django-todo-app"
    image: .
    ports:
      - 8000:8001
    volumes:
      - django_todo_volume:/app
  mysql_db:
    container_name: "django-mysql-db"
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "teste123"
  my_nginx_server:
    container_name: "nginx"
    image: nginx:latest
    ports:
      - 80:80
volumes:
  django_todo_volume:
